# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1 Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # 2 decode google-services.json
      - name: Decode google-services.json
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
        run: echo $FIREBASE_SECRET && echo $FIREBASE_SECRET > app/google-services.json

      # 3 Generate Release APK
      - name: Generate Release APK
        run: bash ./gradlew clean assembleRelease --stacktrace

      # 4 Sign APK
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      # 5 Upload APK as an artifact
      - name: Upload app APK
        uses: actions/upload-artifact@v1
        with:
          name: release.apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
#          # 6 Send email with signed APK
#          - name: ✨ Send email, you star
#            uses: dawidd6/action-send-mail@v1.3.0
#            with:
#              server_address: smtp.gmail.com
#              server_port: 465
#              username: ${{ secrets.MAIL_USERNAME }}
#              password: ${{ secrets.MAIL_PASSWORD }}
#              subject: Release APK ✨
#              body: Checkout this new version of my APK
#              to: ${{ secrets.TO_MAIL_ADDRESS }}
#              from: ${{ secrets.MAIL_ADDRESS }}
